### ISSUE TITLE
no token found on elb sum metrics

### ISSUE THREAD

**Issue by thomasjungblut** [ivx/yet-another-cloudwatch-exporter#45] opened 2019-02-15 10:31 UTC
Hey! Thanks for the great tool :)

Prometheus (we run 2.3.2) has some issues with scraping elb metrics with _sum suffix. My config looks like this:

```
  config.yml: |-
    discovery:
      exportedTagsOnMetrics:
        elb:
        - kubernetes.io/service-name
        - kubernetes.io/cluster/CLUSTER_NAME
      jobs:
      - type: "elb"
        region: eu-west-1
        searchTags:
          - Key: kubernetes.io/cluster/CLUSTER_NAME
            Value: owned
        metrics:
          - name: HealthyHostCount
            statistics:
            - 'Average'
            period: 60
            length: 300
          - name: UnHealthyHostCount
            statistics:
            - 'Average'
            period: 60
            length: 300     
          - name: HTTPCode_Backend_3XX
            statistics:
            - 'Sum'
            period: 60
            length: 900
            delay: 300
            nilToZero: true                   
          - name: HTTPCode_Backend_2XX
            statistics:
            - 'Sum'
            period: 60
            length: 900
            delay: 300
            nilToZero: true
          - name: HTTPCode_Backend_4XX
            statistics:
            - 'Sum'
            period: 60
            length: 900
            delay: 300
            nilToZero: true
          - name: HTTPCode_Backend_5XX
            statistics:
            - 'Sum'
            period: 60
            length: 900
            delay: 300
            nilToZero: true
          - name: HTTPCode_ELB_5XX
            statistics:
            - 'Sum'
            period: 60
            length: 900
            delay: 300
            nilToZero: true
          - name: RequestCount
            statistics:
            - 'Sum'
            period: 60
            length: 900
            delay: 300
            nilToZero: true
          - name: BackendConnectionErrors
            statistics:
            - 'Sum'
            period: 60
            length: 900
            delay: 300
            nilToZero: true
          - name: EstimatedProcessedBytes
            statistics:
            - 'Sum'
            period: 60
            length: 900
            delay: 300
            nilToZero: true
          - name: Latency
            statistics:
            - 'Maximum'
            - 'Average'
            - 'Minimum'
            period: 60
            length: 900
            delay: 300
            nilToZero: true
```

You can check the resulting metrics with:
> cat metrics.txt | promtool check-metrics

which reveals this issue:

```
aws_elb_backend_connection_errors_sum: non-histogram and non-summary metrics should not have "_sum" suffix
aws_elb_estimated_processed_bytes_sum: non-histogram and non-summary metrics should not have "_sum" suffix
aws_elb_httpcode_backend_2_xx_sum: non-histogram and non-summary metrics should not have "_sum" suffix
aws_elb_httpcode_backend_3_xx_sum: non-histogram and non-summary metrics should not have "_sum" suffix
aws_elb_httpcode_backend_4_xx_sum: non-histogram and non-summary metrics should not have "_sum" suffix
aws_elb_httpcode_backend_5_xx_sum: non-histogram and non-summary metrics should not have "_sum" suffix
aws_elb_httpcode_elb_5_xx_sum: non-histogram and non-summary metrics should not have "_sum" suffix
aws_elb_request_count_sum: non-histogram and non-summary metrics should not have "_sum" suffix
```

Can we append some static suffix via config, or always append something to _sum*?

**Comment by thomasjungblut** [comment] 2019-02-15 18:12
@tsupertramp just let me know what you think is the best approach to make this work, I'm happy to create a PR then :)

**Comment by tsupertramp** [comment] 2019-03-04 21:16
Sorry for the late reply. Combination of sickness and vacation.

Wow interesting phenomenon - No quick idea.

I want to merge two prs the next days. I will look into that during these contribution hours as well.

Could you in the meantime please try out the following config:
```
          - name: HTTPCode_Backend_5XX
            statistics:
              - 'Sum'
            period: 300
            length: 300
            nilToZero: true
            disableTimestamp: true
```

**Comment by thomasjungblut** [comment] 2019-03-05 07:07
No worries at all, hope you feel better now. 

Indeed just using  period: 60 & length: 300 seems to fix the problem. Maybe the length: 900 causes some parser issues for some reason.

**Comment by tsupertramp** [comment] 2019-03-05 08:52
Will fix this issue. As it throw an error instead of throwing errors during scraping.

I think we should warn the user that elb metrics are only available for 5m. I think the period of 60 is the problem in your case. As it is not possible to get values for 1m.

Not sure why it does not throw an error but i will find out.

**Comment by tsupertramp** [comment] 2019-03-18 19:58
disableTimestamp is default in next release. This was probably caused by this.

Closing this issue here.

**Closed by tsupertramp** 2019-03-18 19:58 UTC

**Comment by thomasjungblut** [comment] 2019-03-19 07:06
awesome, thank you :)
