### ISSUE TITLE
Grabbing metrics from untagged resources?

### ISSUE THREAD

**Issue by rvandegrift** [ivx/yet-another-cloudwatch-exporter#270] opened 2020-10-28 22:28 UTC
I've setup yace to export metrics from some lambda functions.  It's working, but doesn't pull in metrics from untagged functions.  Is it possible to force collection of metrics from those functions too?  I'd be happy to deal with AWS IDs in that case.

**Comment by thomaspeitz** [comment] 2021-02-26 13:58
This won't be merged. Tags should be used for resources to be able to use this exporter. This is intended behaviour.

**Closed by thomaspeitz** 2021-02-26 13:58 UTC
