### ISSUE TITLE
Sleeping interval messed up?

### ISSUE THREAD

**Issue by BitProcessor** [ivx/yet-another-cloudwatch-exporter#335] opened 2021-03-11 12:49 UTC
Docker image: `quay.io/invisionag/yet-another-cloudwatch-exporter:v0.25.0-alpha`
Startup command: `--config.file=/opt/yace/config.yml --scraping-interval=60 --debug`

With the following config:
```
discovery:
  exportedTagsOnMetrics:
    sqs:
      - env
      - customer
      - message_type
      - queue_type
    lambda:
      - env
      - customer
      - service
  jobs:
  - type: sqs
    period: 60
    length: 60
    regions:
      - eu-west-1
    searchTags:
      - Key: env
        Value: prod
    metrics:
      - name: ApproximateAgeOfOldestMessage
        statistics:
        - Average
      - name: ApproximateNumberOfMessagesVisible
        statistics:
        - Average
      - name: ApproximateNumberOfMessagesNotVisible
        statistics:
        - Average
  - type: lambda
    period: 300
    length: 3600
    regions:
      - eu-west-1
    searchTags:
      - Key: env
        Value: prod
    metrics:
      - name: Invocations 
        statistics:
        - Sum
      - name: Duration
        statistics:
        - Average
      - name: Errors
        statistics:
        - Sum
      - name: IteratorAge
        statistics:
        - Maximum
      - name: ProvisionedConcurrencySpilloverInvocations
        statistics:
        - Sum
        period: 86400
        length: 86400
```

Yace collects the metrics on startup, next says:

```
{"level":"debug","msg":"Metrics scraped.","time":"2021-03-11T12:37:11Z"}
{"level":"debug","msg":"Sleeping at regular sleep interval 86400","time":"2021-03-11T12:37:11Z"}
```

Somehow it seems that that last - metric level - period or length is taken as sleep interval? 

Further testing:
Changing the config to:
```
discovery:
  exportedTagsOnMetrics:
    sqs:
      - env
      - customer
      - message_type
      - queue_type
    lambda:
      - env
      - customer
      - service
  jobs:
  - type: sqs
    period: 60
    length: 60
    regions:
      - eu-west-1
    searchTags:
      - Key: env
        Value: prod
    metrics:
      - name: ApproximateAgeOfOldestMessage
        statistics:
        - Average
      - name: ApproximateNumberOfMessagesVisible
        statistics:
        - Average
      - name: ApproximateNumberOfMessagesNotVisible
        statistics:
        - Average
  - type: lambda
    period: 300
    length: 3600
    regions:
      - eu-west-1
    searchTags:
      - Key: env
        Value: prod
    metrics:
      - name: Invocations 
        statistics:
        - Sum
      - name: Duration
        statistics:
        - Average
      - name: Errors
        statistics:
        - Sum
      - name: IteratorAge
        statistics:
        - Maximum
      - name: ProvisionedConcurrencySpilloverInvocations
        statistics:
        - Sum
        # period: 86400
        # length: 86400
```
Results in:
```
{"level":"debug","msg":"Metrics scraped.","time":"2021-03-11T12:46:07Z"}
{"level":"debug","msg":"Sleeping at regular sleep interval 3600","time":"2021-03-11T12:46:07Z"}
```

Here it seems to have taken the `length: 3600` from the lambda job.

Either I am doing something terribly wrong config-wise, or something is a bit off?

**Comment by BitProcessor** [comment] 2021-03-11 12:58
Looked a bit at the source, could it be coming from here:
```
	//To aviod future timestamp issue we need make sure scrape intervel is atleast at the same level as that of highest job length
	if *scrapingInterval < maxjoblength {
		*scrapingInterval = maxjoblength
	}
```

That seems a bit odd ? 
Shouldn't the scrapingInterval be the minimum job period?

Example: 
- metric A => want to have it scraped every minute
- metric B => want to have it scraped every hour

Result:
- scrape every minute for metric A
- skip scraping metric B 59 times

**Comment by jkuhnv** [comment] 2021-04-15 12:28
I can confirm the behavior in 0.25 is as described. It seems like it's already fixed in 0.26. So maybe this issue can be closed already. But in 0.26 I'm affected by #347, really crazy situation...

**Comment by BitProcessor** [comment] 2021-04-15 12:32
With 0.26.3 and 
```
  - type: lambda
    period: 300
    length: 3600
```
as the only job, it is scraping metrics every 60s 🤷🏻‍♂️ 

Behaviour is different, that is for sure. But shouldn't it simply scrape every 300s in this case?

**Comment by haarchri** [comment] 2021-04-15 16:28
looks like we also have an issue in 0.26.3, or from master

{"level":"debug","msg":"Metrics scraped.","time":"2021-04-15T16:22:54Z"}
{"level":"debug","msg":"Sleeping at regular sleep interval 172800","time":"2021-04-15T16:22:54Z"}

the sleep interval is picked from the biggest length for one metric in config.yml... any ideas ?

**Closed** 2021-07-05 06:17 UTC
