### ISSUE TITLE
Metrics missing with version 0.16.0

### ISSUE THREAD

**Issue by vaishalisutaria** [ivx/yet-another-cloudwatch-exporter#151] opened 2020-04-21 21:37 UTC
We would like to update YACE to 0.16.0. While testing with this update, we noticed that we are not getting following metric which we used to with version 0.14.7.
aws_alb_info

We are also not getting a static metric with namespace `OurCustomMetric`.
Our configuration looks like below:
```
discovery:
  jobs:
  - region: us-west-2
    type: alb
    metrics:
    - name: HealthyHostCount
      statistics: [Average]
      period: 60
      length: 600
      delay: 600
  - type: s3
    region: us-west-2
    metrics:
    - name: BytesUploaded
      statistics: [Sum]
      period: 60
      length: 600
      delay: 600
      additionalDimensions:
      - name: FilterId
        value: EntireBucket
      nilToZero: true
  - type: emr
    region: us-west-2
    metrics:
    - name: AppsRunning
      statistics: [Average]
      period: 60
      length: 600
      delay: 600
static:
  - namespace: OurCustomMetric
    name: Custom-us-west-2
    region: us-west-2
    dimensions:
    - name: Environment
      value: prod
    customTags:
    - Key: account_id
      Value: "12345"
    - Key: environment
      Value: prod
    metrics:
    - name: JobSucceeded
      statistics:
      - 'Sum'
      period: 60
      length: 600
      delay: 600
      nilToZero: true
```
With version 0.16.0, aws_alb_* and aws_alb_tg_* metrics are missing and the aws_emr_* and aws_s3_* metrics seem to be returning only one or two metrics (e.g. aws_s3_info/aws_emr_info)

Custom metric that we get with version 0.14.7 (e.g. TYPE aws_our_custom_metric_job_succeeded_sum) is missing with version 0.16.0

Here is the resultant metrics information with version 0.14.7
```
# HELP aws_alb_info Help is not implemented yet.
# TYPE aws_alb_info gauge
aws_alb_info{name="arn:aws:elasticloadbalancing:us-west-2:12345:loadbalancer/app/abc-i-Porta-Z9D8RUC8TK1K/7c01cdaf0248953e",tag_Category="NETWORK",REDACTED...} 0
aws_alb_info{name="arn:aws:elasticloadbalancing:us-west-2:12345:loadbalancer/abc-stage-BackendP-UP9GY9WZGXBE",tag_Category="APPLICATION",REDACTED...} 0
aws_alb_info{name="arn:aws:elasticloadbalancing:us-west-2:12345:targetgroup/abc-t-Porta-1OPUS4I9RPN2L/af3443a1d2a328dc",tag_Category="NETWORK",REDACTED...} 0
<...more metrics>
# HELP aws_alb_tg_healthy_host_count_average Help is not implemented yet.
# TYPE aws_alb_tg_healthy_host_count_average gauge
aws_alb_tg_healthy_host_count_average{dimension_LoadBalancer="app/abc-i-Porta-Z9D8RUC8TK1K/7c01cdaf0248953e",dimension_TargetGroup="targetgroup/REDACTED..} 1
aws_alb_tg_healthy_host_count_average{dimension_LoadBalancer="app/abc-i-Porta-Z9D8RUC8TK1K/7c01cdaf0248953e",dimension_TargetGroup="targetgroup/REDACTED...} 1
aws_alb_tg_healthy_host_count_average{dimension_LoadBalancer="app/abc-p-Porta-EJM0LMM26AG8/e31df8a9f931e41f",dimension_TargetGroup="targetgroup/REDACTED...} 2
aws_alb_tg_healthy_host_count_average{dimension_LoadBalancer="app/abc-p-Rever-13V2WZZEMU7ZO/986210d501a90433",dimension_TargetGroup="targetgroup/REDACTED...} 2
aws_alb_tg_healthy_host_count_average{dimension_LoadBalancer="app/abc-p-Rever-13V2WZZEMU7ZO/986210d501a90433",dimension_TargetGroup="targetgroup/REDACTED...} 2
aws_alb_tg_healthy_host_count_average{dimension_LoadBalancer="app/abc-p-Rever-1S4S93J86AYHQ/9275d53c70db07b8",dimension_TargetGroup="targetgroup/REDACTED...} 2
aws_alb_tg_healthy_host_count_average{dimension_LoadBalancer="app/abc-s-Rever-TQBYMSWS2LGW/92e719d8ec2c4bf7",dimension_TargetGroup="targetgroup/REDACTED...} 2
<...more metrics>
# HELP aws_emr_info Help is not implemented yet.
# TYPE aws_emr_info gauge
aws_emr_info{name="arn:aws:elasticmapreduce:us-west-2:12345:cluster,...} 0
aws_emr_info{name="arn:aws:elasticmapreduce:us-west-2:12345:cluster,...} 0
<...more metrics>
# HELP aws_our_custom_metric_job_succeeded_sum Help is not implemented yet.
# TYPE aws_our_custom_metric_job_succeeded_sum gauge
aws_our_custom_metric_job_succeeded_sum{custom_tag_account_id="12345",custom_tag_environment="prod",dimension_Environment="prod",name="Custom-us-west-2",region="us-west-2"} 0
# HELP aws_s3_bytes_uploaded_sum Help is not implemented yet.
# TYPE aws_s3_bytes_uploaded_sum gauge
aws_s3_bytes_uploaded_sum{dimension_BucketName="REDACTED",dimension_FilterId="EntireBucket",name="REDACTED",region="us-west-2"} 0
aws_s3_bytes_uploaded_sum{dimension_BucketName="REDACTED",dimension_FilterId="EntireBucket",name="REDACTED",region="us-west-2"} 0
aws_s3_bytes_uploaded_sum{dimension_BucketName="REDACTED",dimension_FilterId="EntireBucket",name="REDACTED",region="us-west-2"} 0
aws_s3_bytes_uploaded_sum{dimension_BucketName="REDACTED",dimension_FilterId="EntireBucket",name="REDACTED",region="us-west-2"} 0
aws_s3_bytes_uploaded_sum{dimension_BucketName="REDACTED",dimension_FilterId="EntireBucket",name="REDACTED",region="us-west-2"} 0
<...more metrics>
# HELP aws_s3_info Help is not implemented yet.
# TYPE aws_s3_info gauge
aws_s3_info{name="REDACTED",...} 0
aws_s3_info{name="REDACTED",...} 0
<...more metrics>
# HELP yace_cloudwatch_requests_total Help is not implemented yet.
# TYPE yace_cloudwatch_requests_total counter
yace_cloudwatch_requests_total 139
```
And below is the resultant metrics information with version 0.16.0
```
# HELP aws_emr_info Help is not implemented yet.
# TYPE aws_emr_info gauge
aws_emr_info{name="arn:aws:elasticmapreduce:us-west-2:12345:cluster/j-3C8O7TIJIVPLT",...} 0
# HELP aws_s3_bytes_uploaded_sum Help is not implemented yet.
# TYPE aws_s3_bytes_uploaded_sum gauge
aws_s3_bytes_uploaded_sum{dimension_BucketName="REDACTED",dimension_FilterId="EntireBucket"...region="us-west-2"} 0
# HELP aws_s3_info Help is not implemented yet.
# TYPE aws_s3_info gauge
aws_s3_info{name="REDACTED",...} 0
# HELP yace_cloudwatch_autoscalingapi_requests_total Help is not implemented yet.
# TYPE yace_cloudwatch_autoscalingapi_requests_total counter
yace_cloudwatch_autoscalingapi_requests_total 0
# HELP yace_cloudwatch_getmetricdata_requests_total Help is not implemented yet.
# TYPE yace_cloudwatch_getmetricdata_requests_total counter
yace_cloudwatch_getmetricdata_requests_total 2
# HELP yace_cloudwatch_getmetricstatistics_requests_total Help is not implemented yet.
# TYPE yace_cloudwatch_getmetricstatistics_requests_total counter
yace_cloudwatch_getmetricstatistics_requests_total 1
# HELP yace_cloudwatch_requests_total Help is not implemented yet.
# TYPE yace_cloudwatch_requests_total counter
yace_cloudwatch_requests_total 6
# HELP yace_cloudwatch_resourcegrouptaggingapi_requests_total Help is not implemented yet.
# TYPE yace_cloudwatch_resourcegrouptaggingapi_requests_total counter
yace_cloudwatch_resourcegrouptaggingapi_requests_total 4

```

Please help us figure out what is causing these metrics to be missing.
Thank you

**Comment by Deepak1100** [comment] 2020-05-08 15:03
we are also facing the same issue.
target group metrics seems to be missing

**Comment by enichols** [comment] 2020-05-29 16:20
We are also seeing this.  Reviewing the diff it seems likely to be related to this [commit](https://github.com/ivx/yet-another-cloudwatch-exporter/commit/2113a7abd1eb9cb045ebd0ae278efc8c8dca0d05).  

cc @daviddetorres can you reproduce this?

**Comment by daviddetorres** [comment] 2020-05-29 16:38
I'll have a look.

**Comment by daviddetorres** [comment] 2020-05-29 17:24
Are metrics also missing in 0.15? Just to narrow down the issue. 

From 0.14 to 0.15 the getMetricsStatistics was replaced by getMetricsData. And from 0.15 to 0.16 the logic to ask for metric was optimized to ask only for metrics with data according to the getMetricsList API call. It would be great to narrow down if it was the change to 0.15 or to 0.16.

Also, can you try with this config values in the metrics?
Period: 300
Length: 3600

I'll try to have a dev window this week and have a look at it.

The change of behaviour in the static config seems strange. As far as I know that part of the code was not changed... can anyone confirm this?

**Comment by enichols** [comment] 2020-05-29 18:06
I just downgraded an instance to 0.15.0-alpha and am able to see targetgroup metrics (eg aws_alb_tg_healthy_host_count_minimum and aws_alb_tg_un_healthy_host_count_maximum) again.

We're using this config successfully on 0.15.0 : 
      - name: UnHealthyHostCount
        statistics: [Maximum]
        period: 600
        length: 600
        addCloudwatchTimestamp: true
      - name: HealthyHostCount
        statistics: [Minimum]
        period: 600
        length: 600
        addCloudwatchTimestamp: true

I tried this on 0.16.0 without success : 
      - name: UnHealthyHostCount
        statistics: [Maximum]
        period: 300
        length: 3600
        addCloudwatchTimestamp: true
      - name: HealthyHostCount
        statistics: [Minimum]
        period: 300
        length: 3600
        addCloudwatchTimestamp: true


I can't speak to that specific static config behavior with custom metrics.  I will note, however, that we have working static configs for non-fargate ECS working in 0.16.0, eg : 
    - namespace: AWS/ECS
      region: us-east-1
      name: redacted
      dimensions:
        - name: ClusterName
          value: redacted-ecs
      metrics:
        - name: CPUUtilization
          statistics: [Average]
          period: 600
          length: 600
          addCloudwatchTimestamp: true

**Comment by abhi4890** [comment] 2020-06-10 11:52
Seems like the changes made as part of (#139 ) resulted in the filtering out of target group metrics. I have raised a PR to fix it (#161 ) @Deepak1100

**Comment by enichols** [comment] 2020-06-15 15:25
I can confirm that this is fixed in 0.18.0

**Comment by thomaspeitz** [comment] 2020-06-16 06:25
@vaishalisutaria could you retry with newest version please? :)

**Comment by nhinds** [comment] 2020-06-16 22:13
I work with @vaishalisutaria. Unfortunately 0.18.0 does not solve this problem for us.

Compared to 0.14.7:
* 0.15.0
  * has all of the same AWS metrics
  * adds some extra `yace_*` metrics for different types of requests
* 0.16.0
  * is missing all `aws_alb_info` and `aws_alb_tg_healthy_host_count_average` metrics
  * is also missing `aws_emr_info` and `aws_s3_info` metrics for EMR jobs or S3 buckets which have not emitted metrics for a while. Previously the `*_info` metrics were *always* emitted, even if there were no metrics for the resources in the time period. We use some of these `*_info` metrics to alert when e.g. a NLB is present but has not had healthy ECS tasks in its target group for a while (we can't alert on unhealthy hosts because unhealthy ECS tasks are immediately removed from the TG), populate filter dropdowns in Grafana, etc.
  * is missing `aws_s3_bytes_uploaded_sum` and `aws_our_custom_metric_job_succeeded_sum` metrics where those have not been valued in CloudWatch for a while, even though we have `nilToZero: true` on those two metrics. They should be present with the value `0`
* 0.17.0 is identical to 0.16.0
* 0.18.0
  * has correct `aws_alb_tg_healthy_host_count_average` metrics
  * is missing `aws_emr_info`, `aws_s3_info`, `aws_s3_bytes_uploaded_sum`, and `aws_our_custom_metric_job_succeeded_sum` metrics in the same way as 0.16.0 and 0.17.0, when metrics are absent
  * is missing `aws_alb_info` metrics for loadbalancers (`name=*:loadbalancer/*`), although the `aws_alb_info` metrics for target groups (`name=*:targetgroup/*`) are present again - possibly because the sample configuration only includes metrics which have target groups in their dimensions?

It seems like there are still two differences:
* `nilToZero: true` is not working
* `*_info` Prometheus metrics are no longer being emitted for resources without recent CloudWatch metrics

**Comment by thomaspeitz** [comment] 2020-06-17 08:57
Thanks will work on that! - This is some nice debugging informations! <3

**Comment by thomaspeitz** [comment] 2020-12-07 07:11
As you fixed it yourself <3 I close this. Thanks again!

**Closed by thomaspeitz** 2020-12-07 07:11 UTC
